top_post_comments:
    - Классный пост
    - Даня пидор
    - Мальчики, классный пост с реддита
    - Сижу на реддите весь день
    - Обожаю реддит
    - Простите
    - Лол
    - Азаза
    - Миленько
    - Приветики
    - Вот бы в 2К18 так делать
    - ISHYGDDT
    - Эх
    - Привет пидоры
    - Хихик
    - Оооо
    - Привет педики UwU

subreddits_of_interest:
    - analog
    - amateurroomporn
    - battlestations
    - tifu
    - shittylifeprotips
    - linuxmemes
    - unixporn
    - linusrants
    - machineporn
    - outoftheloop
    - python
    - gunporn
    - ooer
    - prequelmemes
    - dankmemes
    - worldnews
    - subredditsimulator
    - futurology
    - iama
    - cooking
